sudo: required
dist: xenial
language: python
python: "3.7"

jobs:
  include:
  - stage: code quality
    name: "mypy"
    before_install:
    - pip install mypy lxml
    - pip install -e .

    script:
    - mypy . --txt-report . --scripts-are-modules; cat index.txt; rm index.txt

  - &tests
      stage: test
      name: "Unit Tests w/ Python 3.7"
      before_install:
      - pip install pylint coverage
      - pip install -e .

      script:
      - HOME=/tmp coverage run --source=aioupnp -m unittest -v

      after_success:
      - bash <(curl -s https://codecov.io/bash)

  - <<: *tests
    name: "Unit Tests w/ Python 3.6"
    python: "3.6"
