sudo: required
dist: xenial
language: python
python: "3.7"

before_install:
  - pip install pylint coverage mypy lxml
  - pip install -e .
  - mypy . --txt-report . --scripts-are-modules; cat index.txt; rm index.txt

script:
  - HOME=/tmp coverage run --source=aioupnp -m unittest -v

after_success:
  - bash <(curl -s https://codecov.io/bash)
