sudo: required
dist: xenial
language: python
python: "3.7"

before_install:
  - pip install pylint coverage
  - pip install -e .
#  - pylint aioupnp

script:
  - HOME=/tmp coverage run --source=aioupnp -m unittest -v

after_success:
  - bash <(curl -s https://codecov.io/bash)
