sudo: required
dist: xenial
language: python
python: "3.7"

before_install:
  - pip install pylint coverage mypy
  - pip install -e .

script:
  #  - pylint aioupnp
  - mypy .
  - HOME=/tmp coverage run --source=aioupnp -m unittest -v

after_success:
  - bash <(curl -s https://codecov.io/bash)
